config/routes.rb
Brandslip::Application.routes.draw do

  resources :user_suggestion_proposals

  resources :brandslip_suggestions

  resources :relationships

  resources :ribbits

  resources :contact_us

  resources :user_job_proposals

  resources :jobs

  devise_for :users, :controllers => {:registrations => "registration", :sessions => "devisesession", :passwords => "passwords"}#, :confirmations => "confirmation", :registrations => "registration"}

  root :to => "brandslip#home", constraints: lambda { |r| r.env["warden"].authenticate? }, :as => :dashboard
  root :to => "landing#home", :as => :home
  root :to => "landing#home"
  match "test" => "landing#test", :as => :test
  
  match "new_account_confirm" => "landing#new_account_confirm", :as => :new_account_confirm
  
  match "unfollow" => "relationships#unfollow", :as => :unfollow
  match "admin_login" => "admin#admin_login", :as => :admin_login
  match "/admin/authentication" => "admin#admin_authentication", :as => :admin_authentication
  match "admin_dashboard" => "admin#admin_dashboard", :as => :admin_dashboard
  match "admin_logout" => "admin#admin_logout", :as => :admin_logout
  match "action_on_selected_user" => "admin#action_on_selected_user", :as => :action_on_selected_user
  
  match "search_job" => "brandslip#search_job", :as => :search_job
  match "search_job_filter" => "brandslip#search_job_filter", :as => :search_job_filter
  match "search_job_filter_by_location" => "brandslip#search_job_filter_by_location", :as => :search_job_filter_by_location
  match "search_job_filter_by_valid_for" => "brandslip#search_job_filter_by_valid_for", :as => :search_job_filter_by_valid_for
  match "/user_job_detail/:id" => "brandslip#user_job_detail", :as => :user_job_detail
  match "/job_detail/:id" => "brandslip#job_detail", :as => :job_detail

  match "brands_profile" => "profile#brands_profile", :as => :brands_profile
  match "presenters_profile" => "profile#presenters_profile", :as => :presenters_profile
  match "search_profile_filter" => "profile#search_profile_filter", :as => :search_profile_filter
  match "search_brand_filter" => "profile#search_brand_filter", :as => :search_brand_filter
  
  match "send_message" => "brandslip#send_message", :as => :send_message
  match "presenter_profile" => "brandslip#presenter_profile", :as => :presenter_profile
  match "brand_profile" => "brandslip#brand_profile", :as => :brand_profile
  match "presenters_profile_edit" => "brandslip#presenters_profile_edit", :as => :presenters_profile_edit
  match "brands_profile_edit" => "brandslip#brands_profile_edit", :as => :brands_profile_edit
  match "delete_messages" => "brandslip#delete_messages", :as => :delete_messages
  match "presenters_profile_show" => "profile#presenters_profile_show", :as => :presenters_profile_show
  match "brands_profile_show" => "profile#brands_profile_show", :as => :brands_profile_show  
  match "edit_profile" => "brandslip#edit_profile", :as => :edit_profile1
  match "save_user" => "brandslip#save_user", :as => :save_user
  match "delete_job_proposal" => "brandslip#delete_job_proposal", :as => :delete_job_proposal
  match "show_approve_popup" => "brandslip#show_approve_popup", :as => :show_approve_popup
  match "delete_job" => "jobs#delete_job", :as => :delete_job
  match "edit_job_proposal" => "brandslip#edit_job_proposal", :as => :edit_job_proposal
  match "followings_users" => "brandslip#followings_users", :as => :followings_users
  match "followers_users" => "brandslip#followers_users", :as => :followers_users
  match "add_newsfeed" => "brandslip#add_newsfeed", :as => :add_newsfeed
  match "your_posts" => "brandslip#your_posts", :as => :your_posts
  match "delete_post" => "brandslip#delete_post", :as => :delete_post
  match "/jobs/get_cities" => "brandslip#get_cities", :as => :get_cities
  match "edit_bid" => "brandslip#edit_bid", :as => :edit_bid
  match "get_users_to_msg" => "brandslip#get_users_to_msg", :as => :get_users_to_msg
  match "/presenter_mark_done" => "brandslip#presenter_mark_done", :as => :presenter_mark_done
  match "/brand_mark_done" => "brandslip#brand_mark_done", :as => :brand_mark_done
  match "/review_rating" => "brandslip#review_rating", :as => :review_rating
  match "/suggestion_review_rating" => "brandslip#suggestion_review_rating", :as => :suggestion_review_rating
  match "/add_review_rating" => "brandslip#add_review_rating", :as => :add_review_rating
  match "/add_suggestion_review_rating" => "brandslip#add_suggestion_review_rating", :as => :add_suggestion_review_rating
  match "/review" => "brandslip#review", :as => :review
  match "/transaction_history" => "brandslip#transaction_history", :as => :transaction_history
  
  match "/faq" => "brandslip#faq", :as => :faq
  match "/policies" => "brandslip#policies", :as => :policies
  match "/our_team" => "brandslip#our_team", :as => :our_team
  match "/terms_conditions" => "brandslip#terms_conditions", :as => :terms_conditions
  match "/contact_us_page" => "brandslip#contact_us_page", :as => :contact_us_page

  match "/accept_bid" => "accept_decline_bid#accept_bid", :as => :accept_bid
  match "/delete_bid" => "accept_decline_bid#delete_bid", :as => :delete_bid
  match "/accept_suggestion_bid" => "accept_decline_bid#accept_suggestion_bid", :as => :accept_suggestion_bid
  match "/delete_suggestion_bid" => "accept_decline_bid#delete_suggestion_bid", :as => :delete_suggestion_bid

  resources :payments, only: [:new] do
    post 'add_card', :on => :collection
    post 'add_bank_account', :on => :collection
    post 'credit', :on => :collection
    post 'debit', :on => :collection
  end
  
  match "delete_suggestion" => "brandslip_suggestions#delete_suggestion", :as => :delete_suggestion
  match "search_suggestion" => "brandslip#search_suggestion", :as => :search_suggestion
  match "/suggestion_detail/:id" => "brandslip#suggestion_detail", :as => :suggestion_detail
  match "/user_suggestion_detail/:id" => "brandslip#user_suggestion_detail", :as => :user_suggestion_detail
  match "edit_suggestion_bid" => "brandslip#edit_suggestion_bid", :as => :edit_suggestion_bid
  match "delete_suggestion_proposal" => "brandslip#delete_suggestion_proposal", :as => :delete_suggestion_proposal
  match "search_suggestion_filter" => "brandslip#search_suggestion_filter", :as => :search_suggestion_filter
  match "search_suggestion_filter_by_location" => "brandslip#search_suggestion_filter_by_location", :as => :search_suggestion_filter_by_location
  match "search_suggestion_filter_by_valid_for" => "brandslip#search_suggestion_filter_by_valid_for", :as => :search_suggestion_filter_by_valid_for  
  
  match "j_save_as_interested" => "brandslip#j_save_as_interested", :as => :j_save_as_interested
  match "j_remove_from_interested" => "brandslip#j_remove_from_interested", :as => :j_remove_from_interested
  match "s_save_as_interested" => "brandslip#s_save_as_interested", :as => :s_save_as_interested
  match "s_remove_from_interested" => "brandslip#s_remove_from_interested", :as => :s_remove_from_interested
  match "interested_brandslips" => "brandslip#interested_brandslips", :as => :interested_brandslips
  match "interested_suggestions" => "brandslip#interested_suggestions", :as => :interested_suggestions
  match "delete_interest_brandslip" => "brandslip#delete_interest_brandslip", :as => :delete_interest_brandslip
  match "delete_interest_suggestion" => "brandslip#delete_interest_suggestion", :as => :delete_interest_suggestion

end

app/models/job.rb
class Job < ActiveRecord::Base
  
  attr_accessible :job_category, :job_description, :job_price_fixed_type, :job_price_hour_range, 
                  :job_price_type, :job_skill, :job_start_date, :job_sub_category, :job_title, 
                  :job_valid_for, :job_user_id, :crowd_size, :time, :proof_selector, :city, :state,
                  :followers_subscribers, :online_media_source, :job_type
                
#  validates_presence_of :job_title, :job_description, :job_category, :job_sub_category, :job_start_date,
#                        :job_price_fixed_type, :crowd_size, :time, :proof_selector, :city, :state

#  validates_format_of :job_price_fixed_type, :with =>  /(\$[0-9,]+(\.[0-9]{2})?)/
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  layout "brandslip_layout"
  before_filter :is_profile_complete
  
  # GET /jobs
  # GET /jobs.json
#  def index
#    @jobs = Job.all
#
#    respond_to do |format|
#      format.html # index.html.erb
#      format.json { render json: @jobs }
#    end
#  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])
    respond_to do |format|
      if @job.save
        ribbit = Ribbit.new(:user_id => current_user.id, :content => "#{@job.job_title}")
        ribbit.save
        user_name = User.find(current_user.id).first_name
        user_email = User.find(current_user.id).email
        UserMailer.notifier(user_name, user_email, params[:job][:job_title]).deliver
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
  
  def delete_job
   Rails.logger.debug("#{params[:job_id]}")
   Job.delete_all("id=#{params[:job_id]}")
   
   @delete_job_notifications = UserJobProposal.find_by_sql("select distinct user_id from user_job_proposals where job_id=#{params[:job_id]}")
   @delete_job_notifications.each do |job|
     presenter = Job.find(params[:job_id])
     presenter_user = User.where(:id => presenter.job_user_id)
     presenter_full_name = "#{presenter_user[0].first_name} #{presenter_user[0].last_name}"
     user = User.where(:id => job.user_id)
     brand_full_name = "#{user[0].first_name} #{user[0].last_name}"
     UserMailer.delete_job_notification(user[0].email,brand_full_name, presenter_full_name, job.job_title).deliver
   end        
   UserJobProposal.delete_all("job_id=#{params[:job_id]}")
   render :json => {}
  end
 
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    <% if action == 'edit' && @job.job_type == 1 %>
        var state = $("#job_state").val();
        if(state != ""){
                $.ajax({
                    url: "/jobs/get_cities",
                    type: "post",
                    dataType: "json",
                    data: {
                        "state": state
                    },
                    beforeSend: function() {
                    },
                    complete: function() {
                    },
                    success: function(data) {
                        $("#job_city").find("option:gt(0)").remove();
                        for (var index = 0; index < data['matched_cities'].length; index++) {

                            $("#job_city").append($("<option/>", {
                                                        value: data['matched_cities'][index]['city'],
                                                        text: data['matched_cities'][index]['city']
                                                    }));
                        } 
                        $("#job_city").val('<%= @job.city %>');
                    }
                });          
        }        
        
    <% end %>
    
    $("li#post_job").addClass("active");
    
    $("form.job_form").submit(function(){
      var submit = true;
      var empty_boxes = [];
      $(".job_form input[type='text']:not('.not_required')").each(function(){
        if($(this).val() == ""){
          empty_boxes.push($(this).closest('div.field').find('b').text());
          submit = false;
        }
      });
          
      $(".job_form textarea").each(function(){
        if($(this).val() == ""){
          empty_boxes.push("Description");
          submit = false;
        }
      });
          
      $(".job_form select").each(function(){
        if($(this).val() == ""){
          empty_boxes.push($(this).closest('div.field').find('b').text());
          submit = false;
        }
      });
      
      if(submit == false){
        $("#btn_job_err_msg").click();
        $("div#myModalJobErrorMsg").find(".modal-body").text("Please enter " + empty_boxes.join(', ') +" fields...");
        return false;
      }else{
        if(!$(".chk_terms_and_cond").is(":checked")){
            empty_boxes.push("Accept terms and conditions.");
            submit = false;
            $("#btn_job_err_msg").click();
            $("div#myModalJobErrorMsg").find(".modal-body").text("Please " + empty_boxes.join(', '));            
            return false;
        }
      }
    });
  });
</script> 

<%= form_for(@job, :html => {:class => 'job_form'}) do |f| %>
  <%= f.hidden_field :job_user_id, :value=> current_user.id  %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this BrandSlip from being saved:</h2>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:type] == "public_speaking" %>
    <%= f.hidden_field :job_type, :value=> 1  %>
  <% else %>
    <%= f.hidden_field :job_type, :value=> 2  %>
  <% end %>

  <div style="width: 100%">
    <div style="float: left;width: 50%; padding-right: 190px;">
      <div class="field">
        <b><%= "BrandSlip Title" %></b><br />
        <%= f.text_field :job_title, :class => 'text_field', :size =>30, :maxlength => 50 %>
      </div>
      <br/>
      <div class="field">
        <b><%=  "BrandSlip Description" %></b><br />
        <%= f.text_area :job_description, :id => 'text_field', :rows => '9', :cols => '40', :style => "width:340px" %>
      </div>
      <br/>
      <div class="field">
        <b><%= "Interests" %></b><br />
        <%= f.select(:job_category,
          Jobcategorymaster.all.collect{|s| [s.category, s.id]},

          {:include_blank => '--Select Interests--'}, :class => "selectpicker" ) %>
      </div>
      <br/>
      <% if params[:type] == "public_speaking" %>
        <div class="field">
          <b><%= "Proof Selector"  %></b><br />
            <%= f.select :proof_selector, 
                  ['Have the crowd tweet during your presentation or use a hashtag to promote a brand', 
                   'Provide giveaways supplied by the brand', 'Give out promotional materials supplied by brand',
                   'If you have access to attendees emails, email them information about the brand', 
                   'Other'], 
                 {:include_blank => "Select Proof Selector"}, :class => "selectpicker" %>
        </div>   
      <% else %>
        <div class="field">
          <b><%= "Online Media Source"  %></b><br />
            <%= f.select :online_media_source, ['Youtube', 'Instagram', 'Vine', 'Snapchat'], 
                {:include_blank => "Select Online Media Source"}, :class => "selectpicker" %>
        </div>         
      <% end %>
      <br/>
      <div class="field">
        <b><%= "Age Demographic Criteria" %></b><br />
        <%= f.select(:job_sub_category,
          Jobsubcategorymaster.all.collect{|s| [s.sub_category, s.id]},

          {:include_blank => '--Select Criteria--'}, :class => "selectpicker" ) %>    
      </div> 
      <br/>
    </div>

    <div style="float: right;width: 50%">  
      <div class="field">
        <b><%= "BrandSlip Starting Bid" %></b><br />
        <div>
          <div style="float: left;width: 11px;font-size: 17px;padding-top: 6px;">$</div>
          <div style="float: left;width: 300px"><%= f.text_field :job_price_fixed_type, :class => 'text_field', :size =>25, :placeholder => "45" %></div>
        </div>
      </div>
      <br/>      
      <br/>      
      <br/>      
      <div class="field">
        <b><%= "BrandSlip Valid For (No. of days)" %></b><br />
        <%= f.select :job_valid_for, (1..30).step(1).to_a, {:include_blank => "Select Days"}, :class => "selectpicker" %>
      </div>
      <br/>
      <div class="field">
        <b><%= "BrandSlip Date" %></b><br />
        <%= f.date_select :job_start_date, :class => 'text_field', :size =>30 %>
      </div>
      <br/>
      <% if params[:type] == "public_speaking" %>
        <div class="field">
          <b><%= "Crowd Size" %></b><br />
          <%= f.select :crowd_size, ['Less than 20 people', '20-50 people', '50-80 people', 
                                     '80-100 people', 'Greater than 100 people'], 
                          {:include_blank => "Select Size"}, :class => "selectpicker" %>
        </div>
      <% else %>
        <div class="field">
          <b><%= "Followers/Subscribers" %></b><br />
          <%= f.select :followers_subscribers, ['Less than 50,000', '50,000-100,000', 
                                                 '100,000-500,000', '500,000-1,000,000', '1,000,000+'], 
                         {:include_blank => "Select Size"}, :class => "selectpicker" %>
        </div>      
      <% end %>
      <br/>
      <div class="field">
        <b><%= "Time" %></b><br />
        <%= f.text_field :time, :class => 'text_field', :size =>30 %>
      </div>
      <br/>
      <% if params[:type] == "public_speaking" %>
        <div class="field">
          <b><%= "State" %></b><br />
          <%= f.select(:state,
            State.all.collect{|s| [s.state, s.state]},

            {:include_blank => '--Select State--'}, :class => "selectpicker", :onchange => "populate_cities(this, 'job_city')" ) %>    
        </div> 
        <br/>
        <div class="field">
          <b><%= "City" %></b><br />
          <%= f.select(:city, [],
            {:include_blank => '--Select City--'}, :class => "selectpicker" ) %>    
        </div> 
        <br/>
      <% end %>
    </div>
    <div class="actions" style="padding-bottom: 30px;padding-top: 30px; padding-left: 15%;display: inline-block">
      <div style="padding-bottom: 15px">
        <input type="checkbox" class="chk_terms_and_cond" name="checkbox"/>&nbsp;
        By clicking Create BrandSlip you will agree to 
        <a style="text-decoration: underline" href="<%= terms_conditions_path %>" target=" _blank" >
          Terms/Privacy </a>and
        <a style="text-decoration: underline" href="<%= policies_path %>" target=" _blank" >
          BrandSlip Marketplace Policies.</a>
      </div>
    </div>
    <div class="actions" style="padding-bottom: 30px;padding-left: 30%">
      <%= f.submit "Create BrandSlip", :class => 'btn btn-mini btn-primary', :id => 'sub_job', :style => "color:white" %>
      <%= link_to 'Home', home_path, :class => 'btn btn-mini btn-primary', :style => "color:white;font-size: 13px;"  %>
    </div>
  <% end %>
</div>

<a style="display: none" id="btn_job_err_msg" data-toggle="modal" href="#myModalJobErrorMsg"></a>

<!-- Modal -->
<div class="modal fade" id="myModalJobErrorMsg">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Error Message:</h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-mini" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/jobs/edit.html.erb
<div class="container">
  <div class="row" style="padding-left: 150px">
    <h1 class="formhead conf" style="text-align: center;padding-right: 160px;">Edit Your BrandSlip</h1>
    <br>    
    <%= render 'form', :action => 'edit' %>
  </div>  
</div>

app/views/jobs/new.html.erb
<div class="container">
  <div class="row" style="padding-left: 150px">
    <h1 class="formhead conf" style="text-align: center;padding-right: 160px;">Post Your BrandSlip</h1>
    <br>    
    <%= render 'form', :action => 'new' %>
  </div>
</div>

app/views/jobs/show.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $("li#post_job").addClass("active");
  });
</script> 
<div style="padding-top: 20px">
<p style="font-size: 45px; color: #08C;text-align: center">Your BrandSlip</p>
<p id="notice" style="color: green;text-align: center"><%= notice %></p>
</div>
<div style="padding-left: 40%;padding-top: 20px;font-size: 14px">
  <div style="width: 100%;">
    <div style="width: 50%; float: left;">
      <p>
        <b>BrandSlip Title:</b>
        <%= @job.job_title %>
      </p>

      <p>
        <b>BrandSlip description:</b>
        <%= truncate(@job.job_description, :length => 20) %>
      </p>

      <p>
        <b>BrandSlip category:</b>
        <%= @job.job_category.nil? ? "--" : Jobcategorymaster.find(@job.job_category).category %>
      </p>

      <p>
        <b>BrandSlip sub category:</b>
        <%= @job.job_sub_category.nil? ? "--" : Jobsubcategorymaster.find(@job.job_sub_category).sub_category %>
      </p>
      <% if @job.job_type == 1 %>
        <p>
          <b>BrandSlip Proof Selector:</b>
          <%= @job.proof_selector.nil? ? "--" : @job.proof_selector %>
        </p>
      <% else %>
        <p>
          <b>BrandSlip Online Media Source:</b>
          <%= @job.online_media_source.nil? ? "--" : @job.online_media_source %>
        </p>        
      <% end %>
    </div>

    <div style="width: 50%;">
      <p>
        <b>BrandSlip Starting Bid:</b>
        <%= @job.job_price_fixed_type %>
      </p>
      <p>
        <b>BrandSlip valid for:</b>
        <%= @job.job_valid_for %> Days
      </p>
      <% if @job.job_type == 1 %>
        <p>
          <b>Crowd Size:</b>
          <%= @job.crowd_size %> Days
        </p>
      <% else %>
        <p>
          <b>Followers/Subscribers:</b>
          <%= @job.followers_subscribers %>
        </p>       
      <% end %>
      <p>
        <b>BrandSlip start date:</b>
        <%= @job.job_start_date.nil? ? "--" : @job.job_start_date.strftime("%b %d, %Y") %>
      </p>
      <p>
        <b>Time:</b>
        <%= @job.time.nil? ? "--" : @job.time.strftime("%H:%M:%S") %>
      </p>
    </div>
  </div>
</div>
  <div style="padding-top: 50px;padding-left: 45%;display: inline-block;">
  <%= link_to 'Edit', edit_job_path(@job), :class => 'btn btn-primary', :style => "color:white" %> 
  <%= link_to 'New BrandSlip', new_job_path, :class => 'btn btn-primary', :style => "color:white" %> 
  <%= link_to 'Home', home_path, :class => 'btn btn-primary', :style => "color:white" %> 
  </div>