config/routes.rb
Brandslip::Application.routes.draw do

  resources :user_suggestion_proposals

  resources :brandslip_suggestions

  resources :relationships

  resources :ribbits

  resources :contact_us

  resources :user_job_proposals

  resources :jobs

  devise_for :users, :controllers => {:registrations => "registration", :sessions => "devisesession", :passwords => "passwords"}#, :confirmations => "confirmation", :registrations => "registration"}

  root :to => "brandslip#home", constraints: lambda { |r| r.env["warden"].authenticate? }, :as => :dashboard
  root :to => "landing#home", :as => :home
  root :to => "landing#home"
  match "test" => "landing#test", :as => :test
  
  match "new_account_confirm" => "landing#new_account_confirm", :as => :new_account_confirm
  
  match "unfollow" => "relationships#unfollow", :as => :unfollow
  match "admin_login" => "admin#admin_login", :as => :admin_login
  match "/admin/authentication" => "admin#admin_authentication", :as => :admin_authentication
  match "admin_dashboard" => "admin#admin_dashboard", :as => :admin_dashboard
  match "admin_logout" => "admin#admin_logout", :as => :admin_logout
  match "action_on_selected_user" => "admin#action_on_selected_user", :as => :action_on_selected_user
  
  match "search_job" => "brandslip#search_job", :as => :search_job
  match "search_job_filter" => "brandslip#search_job_filter", :as => :search_job_filter
  match "search_job_filter_by_location" => "brandslip#search_job_filter_by_location", :as => :search_job_filter_by_location
  match "search_job_filter_by_valid_for" => "brandslip#search_job_filter_by_valid_for", :as => :search_job_filter_by_valid_for
  match "/user_job_detail/:id" => "brandslip#user_job_detail", :as => :user_job_detail
  match "/job_detail/:id" => "brandslip#job_detail", :as => :job_detail

  match "brands_profile" => "profile#brands_profile", :as => :brands_profile
  match "presenters_profile" => "profile#presenters_profile", :as => :presenters_profile
  match "search_profile_filter" => "profile#search_profile_filter", :as => :search_profile_filter
  match "search_brand_filter" => "profile#search_brand_filter", :as => :search_brand_filter
  
  match "send_message" => "brandslip#send_message", :as => :send_message
  match "presenter_profile" => "brandslip#presenter_profile", :as => :presenter_profile
  match "brand_profile" => "brandslip#brand_profile", :as => :brand_profile
  match "presenters_profile_edit" => "brandslip#presenters_profile_edit", :as => :presenters_profile_edit
  match "brands_profile_edit" => "brandslip#brands_profile_edit", :as => :brands_profile_edit
  match "delete_messages" => "brandslip#delete_messages", :as => :delete_messages
  match "presenters_profile_show" => "profile#presenters_profile_show", :as => :presenters_profile_show
  match "brands_profile_show" => "profile#brands_profile_show", :as => :brands_profile_show  
  match "edit_profile" => "brandslip#edit_profile", :as => :edit_profile1
  match "save_user" => "brandslip#save_user", :as => :save_user
  match "delete_job_proposal" => "brandslip#delete_job_proposal", :as => :delete_job_proposal
  match "show_approve_popup" => "brandslip#show_approve_popup", :as => :show_approve_popup
  match "delete_job" => "jobs#delete_job", :as => :delete_job
  match "edit_job_proposal" => "brandslip#edit_job_proposal", :as => :edit_job_proposal
  match "followings_users" => "brandslip#followings_users", :as => :followings_users
  match "followers_users" => "brandslip#followers_users", :as => :followers_users
  match "add_newsfeed" => "brandslip#add_newsfeed", :as => :add_newsfeed
  match "your_posts" => "brandslip#your_posts", :as => :your_posts
  match "delete_post" => "brandslip#delete_post", :as => :delete_post
  match "/jobs/get_cities" => "brandslip#get_cities", :as => :get_cities
  match "edit_bid" => "brandslip#edit_bid", :as => :edit_bid
  match "get_users_to_msg" => "brandslip#get_users_to_msg", :as => :get_users_to_msg
  match "/presenter_mark_done" => "brandslip#presenter_mark_done", :as => :presenter_mark_done
  match "/brand_mark_done" => "brandslip#brand_mark_done", :as => :brand_mark_done
  match "/review_rating" => "brandslip#review_rating", :as => :review_rating
  match "/suggestion_review_rating" => "brandslip#suggestion_review_rating", :as => :suggestion_review_rating
  match "/add_review_rating" => "brandslip#add_review_rating", :as => :add_review_rating
  match "/add_suggestion_review_rating" => "brandslip#add_suggestion_review_rating", :as => :add_suggestion_review_rating
  match "/review" => "brandslip#review", :as => :review
  match "/transaction_history" => "brandslip#transaction_history", :as => :transaction_history
  
  match "/faq" => "brandslip#faq", :as => :faq
  match "/policies" => "brandslip#policies", :as => :policies
  match "/our_team" => "brandslip#our_team", :as => :our_team
  match "/terms_conditions" => "brandslip#terms_conditions", :as => :terms_conditions
  match "/contact_us_page" => "brandslip#contact_us_page", :as => :contact_us_page

  match "/accept_bid" => "accept_decline_bid#accept_bid", :as => :accept_bid
  match "/delete_bid" => "accept_decline_bid#delete_bid", :as => :delete_bid
  match "/accept_suggestion_bid" => "accept_decline_bid#accept_suggestion_bid", :as => :accept_suggestion_bid
  match "/delete_suggestion_bid" => "accept_decline_bid#delete_suggestion_bid", :as => :delete_suggestion_bid

  resources :payments, only: [:new] do
    post 'add_card', :on => :collection
    post 'add_bank_account', :on => :collection
    post 'credit', :on => :collection
    post 'debit', :on => :collection
  end
  
  match "delete_suggestion" => "brandslip_suggestions#delete_suggestion", :as => :delete_suggestion
  match "search_suggestion" => "brandslip#search_suggestion", :as => :search_suggestion
  match "/suggestion_detail/:id" => "brandslip#suggestion_detail", :as => :suggestion_detail
  match "/user_suggestion_detail/:id" => "brandslip#user_suggestion_detail", :as => :user_suggestion_detail
  match "edit_suggestion_bid" => "brandslip#edit_suggestion_bid", :as => :edit_suggestion_bid
  match "delete_suggestion_proposal" => "brandslip#delete_suggestion_proposal", :as => :delete_suggestion_proposal
  match "search_suggestion_filter" => "brandslip#search_suggestion_filter", :as => :search_suggestion_filter
  match "search_suggestion_filter_by_location" => "brandslip#search_suggestion_filter_by_location", :as => :search_suggestion_filter_by_location
  match "search_suggestion_filter_by_valid_for" => "brandslip#search_suggestion_filter_by_valid_for", :as => :search_suggestion_filter_by_valid_for  
  
  match "j_save_as_interested" => "brandslip#j_save_as_interested", :as => :j_save_as_interested
  match "j_remove_from_interested" => "brandslip#j_remove_from_interested", :as => :j_remove_from_interested
  match "s_save_as_interested" => "brandslip#s_save_as_interested", :as => :s_save_as_interested
  match "s_remove_from_interested" => "brandslip#s_remove_from_interested", :as => :s_remove_from_interested
  match "interested_brandslips" => "brandslip#interested_brandslips", :as => :interested_brandslips
  match "interested_suggestions" => "brandslip#interested_suggestions", :as => :interested_suggestions
  match "delete_interest_brandslip" => "brandslip#delete_interest_brandslip", :as => :delete_interest_brandslip
  match "delete_interest_suggestion" => "brandslip#delete_interest_suggestion", :as => :delete_interest_suggestion

end

app/models/user_job_proposal.rb
class UserJobProposal < ActiveRecord::Base
  attr_accessible :estimate_delivery_date, :is_place_mine_at_the_top, :is_submit_later, :job_id, :my_earning, 
      :proposal_cost, :proposal_details, :user_id, :user_name
  
  validates_presence_of :proposal_cost, :proposal_details
  
  validates :proposal_cost, :numericality => true, :allow_nil => true
  
  attr_writer :user_name 
end

app/controllers/user_job_proposals_controller.rb
class UserJobProposalsController < ApplicationController
  # GET /user_job_proposals
  # GET /user_job_proposals.json
  layout "brandslip_layout", :only => [:show]
  def index
    @user_job_proposals = UserJobProposal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_job_proposals }
    end
  end

  # GET /user_job_proposals/1
  # GET /user_job_proposals/1.json
  def show
    @user_job_proposal = UserJobProposal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_job_proposal }
    end
  end

  # GET /user_job_proposals/new
  # GET /user_job_proposals/new.json
  def new
    @user_job_proposal = UserJobProposal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_job_proposal }
    end
  end

  # GET /user_job_proposals/1/edit
  def edit
    @user_job_proposal = UserJobProposal.find(params[:id])
  end

  # POST /user_job_proposals
  # POST /user_job_proposals.json
  def create
    @user_job_proposal = UserJobProposal.new(params[:user_job_proposal])
    job_user_name = User.find(params[:user_job_proposal][:user_id]).first_name
    proposal_user_name = User.find(current_user.id).first_name
    job_user_email = User.find(params[:user_job_proposal][:user_id]).email
    job_details = Job.find(params[:user_job_proposal][:job_id])
    proposal_details = params[:user_job_proposal]
#    UserMailer.proposal_notifier(job_user_name, proposal_user_name, job_user_email, job_details, proposal_details).deliver
    respond_to do |format|
      if @user_job_proposal.save  
        format.html { redirect_to @user_job_proposal, notice: 'User job proposal was successfully created.' }
        format.json { render json: @user_job_proposal, status: :created, location: @user_job_proposal }
      else
        format.html { render action: "new" }
        format.json { render json: @user_job_proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_job_proposals/1
  # PUT /user_job_proposals/1.json
  def update
    @user_job_proposal = UserJobProposal.find(params[:id])

    respond_to do |format|
      if @user_job_proposal.update_attributes(params[:user_job_proposal])
        format.html { redirect_to @user_job_proposal, notice: 'User job proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_job_proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_job_proposals/1
  # DELETE /user_job_proposals/1.json
  def destroy
    @user_job_proposal = UserJobProposal.find(params[:id])
    @user_job_proposal.destroy

    respond_to do |format|
      format.html { redirect_to user_job_proposals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_job_proposals_helper.rb
module UserJobProposalsHelper
end

app/views/user_job_proposals/_form.html.erb
<%= form_for(@user_job_proposal) do |f| %>
  <% if @user_job_proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_job_proposal.errors.count, "error") %> prohibited this user_job_proposal from being saved:</h2>

      <ul>
        <% @user_job_proposal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="font-size: 34px;padding-top: 15px;padding-bottom: 10px;margin-right: 50px;">Description of your bid</div>
  <div class="field">

    <%= f.label :proposal_details %><br />
    <li>Don't include contact info?</li>
    <li>Don't know pricing details yet? Ask for more info below and submit? </li>
    <%= f.text_area :proposal_details, :class => 'pro_fields', :id => 'pro_details', :cols => '50%', :rows => 10 %>
  </div>
  <br></br>
  <div class="field">
    <%= f.label :proposal_cost %><br />
    $&nbsp;<%= f.text_field :proposal_cost, :class => 'pro_fields', :placeholder => '  45'  %>
  </div>
  <br></br>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :job_id, :value => params[:id] %>
  <div style="padding-bottom: 15px">
    <input type="checkbox" class="chk_terms_and_cond" name="checkbox"/>&nbsp;
    By clicking Bid you agree to the 
    <a style="text-decoration: underline" href="<%= terms_conditions_path %>" target=" _blank" >
      Terms/Privacy </a>and
    <a style="text-decoration: underline" href="<%= policies_path %>" target=" _blank" >
      BrandSlip Marketplace Policies.</a>
  </div>
  <div class="actions" id = "sub_pro">
    <%= f.submit "Bid", :class=> 'btn btn-primary btn-mini', :id=> '' %>  
    <br></br>  
  </div>
  <span style="color: #808080">Bids are only shown to Presenter.</span>
<% end %>
  
  
  
  <a style="display: none" id="btn_job_err_msg" data-toggle="modal" href="#myModalUserjobErrorMsg"></a>

<!-- Modal -->
<div class="modal fade" id="myModalUserjobErrorMsg">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Error Message:</h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-mini" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/user_job_proposals/edit.html.erb
<h1>Editing user_job_proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_job_proposal %> |
<%= link_to 'Back', user_job_proposals_path %>

app/views/user_job_proposals/index.html.erb
<h1>Listing user_job_proposals</h1>

<table>
  <tr>
    <th>Proposal details</th>
    <th>Proposal cost</th>
    <th>My earning</th>
    <th>Is submit later</th>
    <th>Is place mine at the top</th>
    <th>Estimate delivery date</th>
    <th>BrandSlip</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_job_proposals.each do |user_job_proposal| %>
  <tr>
    <td><%= user_job_proposal.proposal_details %></td>
    <td><%= user_job_proposal.proposal_cost %></td>
    <td><%= user_job_proposal.my_earning %></td>
    <td><%= user_job_proposal.is_submit_later %></td>
    <td><%= user_job_proposal.is_place_mine_at_the_top %></td>
    <td><%= user_job_proposal.estimate_delivery_date %></td>
    <td><%= user_job_proposal.job_id %></td>
    <td><%= user_job_proposal.user_id %></td>
    <td><%= link_to 'Show', user_job_proposal %></td>
    <td><%= link_to 'Edit', edit_user_job_proposal_path(user_job_proposal) %></td>
    <td><%= link_to 'Destroy', user_job_proposal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User Brands proposal', new_user_job_proposal_path %>

app/views/user_job_proposals/new.html.erb
<h1>New user_BrandSlip_proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', user_job_proposals_path %>

app/views/user_job_proposals/show.html.erb
<div style="padding-top: 35px; width: 100%; text-align: center;font-size: 14px">
  <span style="font-size: 35px; padding-top: 15px">Your Job Proposal</span>
<p id="notice"><%= notice %></p>

<p>
  <b>Proposal details:</b>
  <%= @user_job_proposal.proposal_details %>
</p>

<p>
  <b>Proposal cost:</b>
  $<%= @user_job_proposal.proposal_cost %>
</p>


<%= link_to 'Home', home_path, :class => 'btn btn-mini btn-primary' %>
</div>