config/routes.rb
Brandslip::Application.routes.draw do

  resources :user_suggestion_proposals

  resources :brandslip_suggestions

  resources :relationships

  resources :ribbits

  resources :contact_us

  resources :user_job_proposals

  resources :jobs

  devise_for :users, :controllers => {:registrations => "registration", :sessions => "devisesession", :passwords => "passwords"}#, :confirmations => "confirmation", :registrations => "registration"}

  root :to => "brandslip#home", constraints: lambda { |r| r.env["warden"].authenticate? }, :as => :dashboard
  root :to => "landing#home", :as => :home
  root :to => "landing#home"
  match "test" => "landing#test", :as => :test
  
  match "new_account_confirm" => "landing#new_account_confirm", :as => :new_account_confirm
  
  match "unfollow" => "relationships#unfollow", :as => :unfollow
  match "admin_login" => "admin#admin_login", :as => :admin_login
  match "/admin/authentication" => "admin#admin_authentication", :as => :admin_authentication
  match "admin_dashboard" => "admin#admin_dashboard", :as => :admin_dashboard
  match "admin_logout" => "admin#admin_logout", :as => :admin_logout
  match "action_on_selected_user" => "admin#action_on_selected_user", :as => :action_on_selected_user
  
  match "search_job" => "brandslip#search_job", :as => :search_job
  match "search_job_filter" => "brandslip#search_job_filter", :as => :search_job_filter
  match "search_job_filter_by_location" => "brandslip#search_job_filter_by_location", :as => :search_job_filter_by_location
  match "search_job_filter_by_valid_for" => "brandslip#search_job_filter_by_valid_for", :as => :search_job_filter_by_valid_for
  match "/user_job_detail/:id" => "brandslip#user_job_detail", :as => :user_job_detail
  match "/job_detail/:id" => "brandslip#job_detail", :as => :job_detail

  match "brands_profile" => "profile#brands_profile", :as => :brands_profile
  match "presenters_profile" => "profile#presenters_profile", :as => :presenters_profile
  match "search_profile_filter" => "profile#search_profile_filter", :as => :search_profile_filter
  match "search_brand_filter" => "profile#search_brand_filter", :as => :search_brand_filter
  
  match "send_message" => "brandslip#send_message", :as => :send_message
  match "presenter_profile" => "brandslip#presenter_profile", :as => :presenter_profile
  match "brand_profile" => "brandslip#brand_profile", :as => :brand_profile
  match "presenters_profile_edit" => "brandslip#presenters_profile_edit", :as => :presenters_profile_edit
  match "brands_profile_edit" => "brandslip#brands_profile_edit", :as => :brands_profile_edit
  match "delete_messages" => "brandslip#delete_messages", :as => :delete_messages
  match "presenters_profile_show" => "profile#presenters_profile_show", :as => :presenters_profile_show
  match "brands_profile_show" => "profile#brands_profile_show", :as => :brands_profile_show  
  match "edit_profile" => "brandslip#edit_profile", :as => :edit_profile1
  match "save_user" => "brandslip#save_user", :as => :save_user
  match "delete_job_proposal" => "brandslip#delete_job_proposal", :as => :delete_job_proposal
  match "show_approve_popup" => "brandslip#show_approve_popup", :as => :show_approve_popup
  match "delete_job" => "jobs#delete_job", :as => :delete_job
  match "edit_job_proposal" => "brandslip#edit_job_proposal", :as => :edit_job_proposal
  match "followings_users" => "brandslip#followings_users", :as => :followings_users
  match "followers_users" => "brandslip#followers_users", :as => :followers_users
  match "add_newsfeed" => "brandslip#add_newsfeed", :as => :add_newsfeed
  match "your_posts" => "brandslip#your_posts", :as => :your_posts
  match "delete_post" => "brandslip#delete_post", :as => :delete_post
  match "/jobs/get_cities" => "brandslip#get_cities", :as => :get_cities
  match "edit_bid" => "brandslip#edit_bid", :as => :edit_bid
  match "get_users_to_msg" => "brandslip#get_users_to_msg", :as => :get_users_to_msg
  match "/presenter_mark_done" => "brandslip#presenter_mark_done", :as => :presenter_mark_done
  match "/brand_mark_done" => "brandslip#brand_mark_done", :as => :brand_mark_done
  match "/review_rating" => "brandslip#review_rating", :as => :review_rating
  match "/suggestion_review_rating" => "brandslip#suggestion_review_rating", :as => :suggestion_review_rating
  match "/add_review_rating" => "brandslip#add_review_rating", :as => :add_review_rating
  match "/add_suggestion_review_rating" => "brandslip#add_suggestion_review_rating", :as => :add_suggestion_review_rating
  match "/review" => "brandslip#review", :as => :review
  match "/transaction_history" => "brandslip#transaction_history", :as => :transaction_history
  
  match "/faq" => "brandslip#faq", :as => :faq
  match "/policies" => "brandslip#policies", :as => :policies
  match "/our_team" => "brandslip#our_team", :as => :our_team
  match "/terms_conditions" => "brandslip#terms_conditions", :as => :terms_conditions
  match "/contact_us_page" => "brandslip#contact_us_page", :as => :contact_us_page

  match "/accept_bid" => "accept_decline_bid#accept_bid", :as => :accept_bid
  match "/delete_bid" => "accept_decline_bid#delete_bid", :as => :delete_bid
  match "/accept_suggestion_bid" => "accept_decline_bid#accept_suggestion_bid", :as => :accept_suggestion_bid
  match "/delete_suggestion_bid" => "accept_decline_bid#delete_suggestion_bid", :as => :delete_suggestion_bid

  resources :payments, only: [:new] do
    post 'add_card', :on => :collection
    post 'add_bank_account', :on => :collection
    post 'credit', :on => :collection
    post 'debit', :on => :collection
  end
  
  match "delete_suggestion" => "brandslip_suggestions#delete_suggestion", :as => :delete_suggestion
  match "search_suggestion" => "brandslip#search_suggestion", :as => :search_suggestion
  match "/suggestion_detail/:id" => "brandslip#suggestion_detail", :as => :suggestion_detail
  match "/user_suggestion_detail/:id" => "brandslip#user_suggestion_detail", :as => :user_suggestion_detail
  match "edit_suggestion_bid" => "brandslip#edit_suggestion_bid", :as => :edit_suggestion_bid
  match "delete_suggestion_proposal" => "brandslip#delete_suggestion_proposal", :as => :delete_suggestion_proposal
  match "search_suggestion_filter" => "brandslip#search_suggestion_filter", :as => :search_suggestion_filter
  match "search_suggestion_filter_by_location" => "brandslip#search_suggestion_filter_by_location", :as => :search_suggestion_filter_by_location
  match "search_suggestion_filter_by_valid_for" => "brandslip#search_suggestion_filter_by_valid_for", :as => :search_suggestion_filter_by_valid_for  
  
  match "j_save_as_interested" => "brandslip#j_save_as_interested", :as => :j_save_as_interested
  match "j_remove_from_interested" => "brandslip#j_remove_from_interested", :as => :j_remove_from_interested
  match "s_save_as_interested" => "brandslip#s_save_as_interested", :as => :s_save_as_interested
  match "s_remove_from_interested" => "brandslip#s_remove_from_interested", :as => :s_remove_from_interested
  match "interested_brandslips" => "brandslip#interested_brandslips", :as => :interested_brandslips
  match "interested_suggestions" => "brandslip#interested_suggestions", :as => :interested_suggestions
  match "delete_interest_brandslip" => "brandslip#delete_interest_brandslip", :as => :delete_interest_brandslip
  match "delete_interest_suggestion" => "brandslip#delete_interest_suggestion", :as => :delete_interest_suggestion

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrandSlip Admin</title>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/gif" href="/assets/favicon.png">
</head>
<body class="page-header-fixed">
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Brandslip" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Brandslip" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/brandslip_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="https://js.balancedpayments.com/v1/balanced.js"></script>
  <title>Brandslip</title>
  <%= stylesheet_link_tag "application", "brandslip", "contact_us","landing", "bootstrap-responsive", "bootstrap-responsive.min", "bootstrap", "dashboard", "jobs", "d_green", :media => "all" %>
  <%= javascript_include_tag "application", "jquery","jquery-1.8.2", "jquery-ui.min", "jquery.dataTables", "all", "bootstrap", "bootstrap-datepicker", "jquery.raty.min" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
  <link rel="icon" type="image/gif" href="/assets/favicon.png">
  <script type="text/css">



  </script>


      <script type="text/javascript">
    balanced.init('/v1/marketplaces/TEST-MP1y8mqAL3IIHgZ6u2lr9vS2');
</script>
</head>
<body class="">
  <%= javascript_tag do %>
    var dashboard_path = <%= dashboard_url.to_json.html_safe %>;
  <% end %>   
  <div id="wrap">
    <div class="container-liquid">
      <div class="navbar navbar-inverse top-navigation" style="padding: 0px; margin-bottom: 0px; background-color: #468FD3;font-size: 14px; border-radius: 0">
        
        <div class="span3" style="background-color: #3473A8; font-size: 30px; margin-left: 0;">
          <a class="navbar-brand brand" style="color:white; margin: 0 auto; float: none" href="<%= dashboard_path %>">BrandSlip</a>
        </div>

        <div class="nav-collapse collapse navbar-inverse-collapse">
          <ul class="nav navbar-nav navbar-left">
            <% if current_user.user_type == 1 %>
              <li>
                <a href="#">
                  <span class="icon-search"></span> Find BrandSlips<span class="caret"></span>
                </a>
                <ul>
                  <li><a href="<%= search_job_path(:job_type => 'public_speaking') %>">Search for Public Speaking BrandSlips</a></li>
                  <li><a href="<%= search_job_path(:job_type => 'online') %>">Search for Online BrandSlips (Youtube, Vine, Instagram)</a></li>
                </ul>
              </li>
            <% end %>
            <% if current_user.user_type == 2  %>
              <li>
                <a href="#">
                  <span class="icon-mail"></span> Post Your BrandSlip<span class="caret"></span>
                </a>
                <ul>
                  <li><a href="<%= new_job_path(:type => 'public_speaking') %>">Public Speaking BrandSlip</a></li>
                  <li><a href="<%= new_job_path(:type => 'online') %>">Online BrandSlip</a></li>
                </ul>
              </li>
            <% end %>

            <% if current_user.user_type == 1 %>
              <li>
                <a href="#"><span class="icon-mail"></span> Post Your BrandSlip Suggestion<span class="caret"></span></a>
                <ul >
                  <li><a href="<%= new_brandslip_suggestion_path(:type => 'public_speaking') %>">Public Speaking BrandSlip Suggestion</a></li>
                  <li><a href="<%= new_brandslip_suggestion_path(:type => 'online') %>">Online BrandSlip Suggestion (Youtube, Vine, Instagram)</a></li>
                </ul>           
              </li>
            <% elsif current_user.user_type == 2 %>
              <li>
                <a href="#"><span class="icon-search"></span> Find BrandSlip Suggestions<span class="caret"></span></a>
                <ul>
                <li><a href="<%= search_suggestion_path(:type => 'public_speaking') %>">Public Speaking BrandSlip Suggestions</a></li>
                <li><a href="<%= search_suggestion_path(:type => 'online') %>">Online BrandSlip Suggestions</a></li>
                </ul>           
              </li>
            <% end %>

            <% if current_user.user_type == 1 %>
              <li id="brandslip_profile"><a href="<%= presenter_profile_path %>"><span class="icon-user"></span> Presenter Profiles</a></li>
            <% elsif current_user.user_type == 2 %>
              <li id="brandslip_profile"><a href="<%= brand_profile_path %>"><span class="icon-user"></span> Brands Profiles</a></li>
            <% end %>

            <li id="contact_us"><a href="<%= contact_us_page_path %>">Contact Us</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right pull-right">
            <li>
              <a href="<%= edit_profile1_path %>">
                <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %><span class="caret"></span>
              </a>
              <ul>
                <li><a href="<%= edit_profile1_path %>">Edit Profile</a></li>
                <li><a href="<%= review_path %>">Reviews</a></li>
                <li><a href="<%= transaction_history_path %>">Transaction History</a></li>
                <% if current_user.user_type == 1 %>
                  <li><a href="<%= interested_brandslips_path %>">BrandSlips I’m Interested In</a></li>
                <% elsif current_user.user_type == 2 %>
                  <li><a href="<%= interested_suggestions_path %>">BrandSlip Suggestions I’m Interested In</a></li>
                <% end %>
              </ul>
            </li>
            <li>
              <a class="btn-danger" href="<%= destroy_user_session_path %> ">Logout</a>
            </li>
          </ul>
        </div>
        
      </div>
    </div>
    <%= yield %>
  </div>
 
  <div id="footer" class="footer" style="width: 100%;background-color:#418BCA;font-size: 11px; position: fixed; bottom: 0; left: 0; -webkit-transform: translateZ(0)">
    <div class="container" >
      <div style="text-align: center; color: white; padding-top: 15px;font-size: 13px"class="container">
        <span><a style="color: white;text-decoration: none" href="<%= contact_us_page_path %>">Contact Us</a></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span>Our Team</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span>FAQ</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span>Terms</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span>Privacy Policies</span>&nbsp;&nbsp;
        <span id=""><a href="//www.facebook.com/brandslip" target="_blank"><img src = "/assets/facebook_w.png" size = "25X25" style="width: 25px"/></a></span>
        <span id=""><a href="//www.twitter.com/brandslip" target="_blank"><img src = "/assets/twitter_w.png" size = "30x30" style="width: 30px"/></a></span>
      </div> 
    </div>
  </div>   
</body>
</html>

app/views/layouts/landing_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>BrandSlip</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Base scripts -->
	<script type="text/javascript" src="/assets/jquery.js"></script>
	<script type="text/javascript" src="/assets/modernizr-latest.js"></script>
	<script type="text/javascript" src="/assets/application.js"></script>
        <link rel="icon" type="image/gif" href="/assets/favicon.png">
	<!-- Styles -->
	<link rel="stylesheet" type="text/css" href="/assets/bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="/assets/bootstrap-responsive.css" />
	<link rel="stylesheet" type="text/css" href="/assets/bootstrap-responsive.min.css" />
	<link rel="stylesheet" type="text/css" href="/assets/style.css" />
	<link rel="stylesheet" type="text/css" href="/assets/flexslider.css" />
	<link rel="stylesheet" type="text/css" href="/assets/datepicker.css" />
	<link rel="stylesheet" type="text/css" href="/assets/application.css" />

	<!-- Fonts -->
	<link rel="stylesheet" type="text/css" href="/assets/font-awesome.css" />
	<link href='http://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Nunito:300,400,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
 
</head>
<body style="background-color: lightgray" class="home">
  <%= javascript_tag do %>
    var dashboard_path = <%= dashboard_url.to_json.html_safe %>;
  <% end %> 

  <%= yield %>

</body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="https://js.balancedpayments.com/v1/balanced.js"></script>
	<title>BrandSlip</title>
        <meta charset="utf-8">
	<!-- viewport --> 
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!--  including stylesheets-->
	<%= stylesheet_link_tag "application", "profile", "d_green", "bootstrap-responsive", "bootstrap-responsive.min", "bootstrap", :media => "all" %>
        <link rel="icon" type="image/gif" href="/assets/favicon.png">
	<!-- google fonts-->
	<link href='http://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
 <script type="text/javascript">
    balanced.init('/v1/marketplaces/TEST-MP1y8mqAL3IIHgZ6u2lr9vS2');
</script>
</head>
<body>

<%= yield %>

<!-- including js -->
<script type="text/javascript" src="/assets/application.js"></script>
<script type="text/javascript" src="/assets/jquery.js"></script>
<script type="text/javascript" src="/assets/jquery-1.8.2.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="/assets/gmap3.min.js"></script>
<script type="text/javascript" src="/assets/additional-scripts.min.js"></script>
<script type="text/javascript" src="/assets/profile_custom.js"></script>
<script type="text/javascript" src="/assets/profile.js"></script>
<script type="text/javascript" src="/assets/jquery.raty.min.js"></script>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>  
</body>
</html>